[versions]
kermit = "2.0.6"
kotlin = "2.2.0"
kotlinx-coroutines = "1.10.2"
compose = "1.9.0+dev2644"
jna = "5.17.0"
platformtools = "0.4.0"

[libraries]
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
platformtools-core = { module = "io.github.kdroidfilter:platformtools.core", version.ref = "platformtools" }
kmp-log = { module = "io.github.kdroidfilter:kmplog", version = "0.3.0" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vannitktech-maven-publish = {id = "com.vanniktech.maven.publish", version = "0.33.0"}
dokka = { id = "org.jetbrains.dokka" , version = "2.0.0"}